#!/bin/sh

# Copyright 2014 Akira Midorikawa
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

EXPECTED="${SOURCE_PATH}/share/alice.txt"

fail() {
  ${ROOT_PATH}/tool/umount disk
  exit 1
}

mkdir -p disk
${ROOT_PATH}/tool/mount disk.img disk

diff -u disk/tmp/alice.txt ${EXPECTED} 1>&2 || fail
${ROOT_PATH}/tool/umount disk
