#!/bin/sh

# Copyright 2014 Akira Midorikawa
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

mkdir -p disk
${ROOT_PATH}/tool/mount disk.img disk

mkdir -p disk/sbin
cp $BUILD_PATH/unistd_execve disk/sbin
cp $BUILD_PATH/unistd_execve_new disk/sbin

${ROOT_PATH}/tool/umount disk
