#!/usr/bin/env bash

# Copyright 2016 Akira Midorikawa
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu

# FUSE isn't mounted immediately in Mac OS X.
# So polling is performed to ensure whether FUSE is mounted or not.
osx-fuse-mfs() {
  if [ "$#" -ne 2 ]; then
    echo "USAGE: $0 device mount_point" >&2
    exit 1
  fi

  local device=$1
  local mount_point=$2
  local check_file=${mount_point}/.fuse-mfs

  touch ${check_file}
  fuse-mfs -osync ${device} ${mount_point}

  local retry=0

  while [ -f "${check_file}" ]; do
    sleep 0.01

    if [ "$retry" -eq 100 ]; then
      echo "couldn't mount device" >&2
      exit 1
    fi

    retry=$((retry+1))
  done
}

case "$(uname)" in
Darwin)
  osx-fuse-mfs "$@"
  ;;
*)
  exec fuse-mfs "$@"
  ;;
esac
