#!/usr/bin/env bash

set -exu

QEMU_VERSION="2.5.1.1"
QEMU_FILENAME="qemu-${QEMU_VERSION}.tar.bz2"
QEMU_URL="http://wiki.qemu-project.org/download/${QEMU_FILENAME}"

RUBY_VERSION="2.3.1"
RUBY_FILENAME="ruby-${RUBY_VERSION}.tar.bz2"
RUBY_URL="https://rubies.travis-ci.org/ubuntu/14.04/x86_64/${RUBY_FILENAME}"

FUSE_MFS_VERSION="0.4"
FUSE_MFS_FILENAME="fuse-mfs_0.4-d25f058_amd64.deb"
FUSE_MFS_URL="https://github.com/redcap97/fuse-mfs/releases/download/v${FUSE_MFS_VERSION}/${FUSE_MFS_FILENAME}"

wget ${QEMU_URL}
tar jxf ${QEMU_FILENAME}
pushd $(basename ${QEMU_FILENAME} .tar.bz2)
./configure --target-list=arm-softmmu,arm-linux-user
make -j4
sudo make install
popd

wget ${RUBY_URL}
sudo tar jxf ${RUBY_FILENAME} --strip-components=1 -C /usr

wget ${FUSE_MFS_URL}
sudo dpkg -i ${FUSE_MFS_FILENAME}

sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi
